// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace vpsrestapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Models.Circuit", b =>
                {
                    b.Property<int>("circuitId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("alt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("circuitRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("lat")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("lng")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("circuitId");

                    b.ToTable("Circuits");
                });

            modelBuilder.Entity("Models.Driver", b =>
                {
                    b.Property<int>("driverId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dob")
                        .HasColumnType("Date");

                    b.Property<string>("driverRef")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("forename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("nationality")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("number")
                        .HasColumnType("TEXT");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.HasKey("driverId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Models.DriverStanding", b =>
                {
                    b.Property<int>("driverStandingsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("driverId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("points")
                        .HasColumnType("REAL");

                    b.Property<int?>("position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("positionText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("raceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("driverStandingsId");

                    b.HasIndex("driverId");

                    b.HasIndex("raceId");

                    b.ToTable("DriverStandings");
                });

            modelBuilder.Entity("Models.LapTime", b =>
                {
                    b.Property<int?>("raceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("driverId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("lap")
                        .HasColumnType("INTEGER");

                    b.Property<float>("milliseconds")
                        .HasColumnType("REAL");

                    b.Property<int>("position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("raceId", "driverId", "lap");

                    b.HasIndex("driverId");

                    b.ToTable("LapTimes");
                });

            modelBuilder.Entity("Models.Race", b =>
                {
                    b.Property<int>("raceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("circuitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("date")
                        .HasColumnType("Date");

                    b.Property<string>("fp1_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("fp1_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("fp2_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("fp2_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("fp3_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("fp3_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("quali_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("quali_time")
                        .HasColumnType("TEXT");

                    b.Property<int>("round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sprint_date")
                        .HasColumnType("TEXT");

                    b.Property<string>("sprint_time")
                        .HasColumnType("TEXT");

                    b.Property<string>("time")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("raceId");

                    b.HasIndex("circuitId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Models.DriverStanding", b =>
                {
                    b.HasOne("Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("driverId");

                    b.HasOne("Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("raceId");

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Models.LapTime", b =>
                {
                    b.HasOne("Models.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("driverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("raceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Models.Race", b =>
                {
                    b.HasOne("Models.Circuit", "Circuit")
                        .WithMany()
                        .HasForeignKey("circuitId");

                    b.Navigation("Circuit");
                });
#pragma warning restore 612, 618
        }
    }
}
